# Configuracion de patrocinio para este repo.
# Si quieres apoyar el desarrollo, descomenta una entrada y pon tu usuario.

github: [Nakly1]
# patreon: # nombre-patreon
# open_collective: # nombre-collective
# ko_fi: # nombre-kofi
# tidelift: # plataforma-name/package-name
# community_bridge: # nombre-proyecto
# liberapay: # nombre-liberapay
# issuehunt: # nombre-issuehunt
# otechie: # nombre-otechie
# lfx_crowdfunding: # nombre-proyecto
# polar: # nombre-polar
# buy_me_a_coffee: # nombre-bmac
# thanks_dev: # u/nombre-user
custom: []
